#!/usr/bin/env python
# -*- coding: utf-8 -*-

instruments = [
    ["(kick|kik|BassDrum)", 36],
    ["(side|rim)", 37],
    ["esnare", 40],
    ["snare", 38],
    ["clap", 39],
    ["low.?fl.*tom", 41],
    ["(CHH|HHC|Hat.?closed|HH.*closed|Closed.+Hat)", 42],
    ["hi.?fl.*tom", 43],
    ["(hh.*foot|foot.*hh)", 44],
    ["(low.?tom|tom.?low)", 45],
    ["(OHH|HHO|Hat.?Open|HH.*Open|Open.+Hat)", 46],
    ["low.*mid.*tom", 47],
    ["hi.*mid.*tom", 48],
    ["crash", 49],
    ["(hi.*tom|tom.?hi)", 50],
    ["ride", 51],
    ["tamb", 54],
    ["splash", 55],
    ["cowbell", 56],
    ["vibra", 58],
    ["(hi.*bongo|bongo.*hi)", 60],
    ["bongo", 61],
    ["(mut.*conga|conga.*mut)", 62],
    ["(open.*conga|conga.*open)", 63],
    ["hi.*conga", 62],
    ["conga", 64],
    ["(hi.*agogo|agogo.*hi)", 67],
    ["agogo", 68],
    ["cabasa", 69],
    ["mara?cas", 70],
    ["(sho.*whistle|whistle.*sho)", 71],
    ["whistle", 72],
    ["(lon.*guiro|guiro.*lon)", 73],
    ["(guiro)", 74],
    ["clav", 75],
    ["hi.*woodblock", 76],
    ["woodblock", 77],
    ["shaker", 82],
    ["(mut.*triangl|triangl.*mut)", 80],
    ["triangl", 81],
    # last try
    ["hat", 42],
    ["tom", 45],
    ["cym", 51],
    ["\\WBD", 36],
    ["\\WSD", 38],
    ["\\WCH", 42],
    ["\\WOH", 46],
]

names = {
    27: "High Q / Laser",
    28: "Slap / Whip",
    29: "Scratch Push",
    30: "Scratch Pull",
    31: "Sticks",
    32: "Square Click",
    33: "Metronome Click",
    34: "Metronome Bell",
    35: "Acoustic Bass Drum",
    36: "Bass Drum 1",
    37: "Side Stick",
    38: "Acoustic Snare",
    39: "Hand Clap",
    40: "Electric Snare",
    41: "Low Floor Tom",
    42: "Closed Hi Hat",
    43: "High Floor Tom",
    44: "Pedal Hi-Hat",
    45: "Low Tom",
    46: "Open Hi-Hat",
    47: "Low-Mid Tom",
    48: "Hi Mid Tom",
    49: "Crash Cymbal 1",
    50: "High Tom",
    51: "Ride Cymbal 1",
    52: "Chinese Cymbal",
    53: "Ride Bell",
    54: "Tambourine",
    55: "Splash Cymbal",
    56: "Cowbell",
    57: "Crash Cymbal 2",
    58: "Vibraslap",
    59: "Ride Cymbal 2",
    60: "Hi Bongo",
    61: "Low Bongo",
    62: "Mute Hi Conga",
    63: "Open Hi Conga",
    64: "Low Conga",
    65: "High Timbale",
    66: "Low Timbale",
    67: "High Agogo",
    68: "Low Agogo",
    69: "Cabasa",
    70: "Maracas",
    71: "Short Whistle",
    72: "Long Whistle",
    73: "Short Guiro",
    74: "Long Guiro",
    75: "Claves",
    76: "Hi Wood Block",
    77: "Low Wood Block",
    78: "Mute Cuica",
    79: "Open Cuica",
    80: "Mute Triangle",
    81: "Open Triangle",
    82: "Shaker",
    83: "Jingle Bell",
    84: "Belltree",
    85: "Castanets",
    86: "Mute Surdo",
    87: "Open Surdo",
}
